/**
 * @module gateway/protocol/schema/types
 * JSDoc typedefs for protocol schema types. These were originally TypeScript Static<> type extractions.
 * In JavaScript, schema validation is performed at runtime via Ajv; these typedefs exist for
 * editor tooling and documentation only.
 *
 * Each typedef corresponds to the inferred shape of its matching TypeBox schema (e.g.
 * ConnectParams = the shape validated by ConnectParamsSchema).
 * @typedef {import("@sinclair/typebox").Static<typeof import("./frames.js").ConnectParamsSchema>} ConnectParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./frames.js").HelloOkSchema>} HelloOk
 * @typedef {import("@sinclair/typebox").Static<typeof import("./frames.js").RequestFrameSchema>} RequestFrame
 * @typedef {import("@sinclair/typebox").Static<typeof import("./frames.js").ResponseFrameSchema>} ResponseFrame
 * @typedef {import("@sinclair/typebox").Static<typeof import("./frames.js").EventFrameSchema>} EventFrame
 * @typedef {import("@sinclair/typebox").Static<typeof import("./frames.js").GatewayFrameSchema>} GatewayFrame
 * @typedef {import("@sinclair/typebox").Static<typeof import("./frames.js").ErrorShapeSchema>} ErrorShape
 * @typedef {import("@sinclair/typebox").Static<typeof import("./frames.js").TickEventSchema>} TickEvent
 * @typedef {import("@sinclair/typebox").Static<typeof import("./frames.js").ShutdownEventSchema>} ShutdownEvent
 * @typedef {import("@sinclair/typebox").Static<typeof import("./snapshot.js").SnapshotSchema>} Snapshot
 * @typedef {import("@sinclair/typebox").Static<typeof import("./snapshot.js").PresenceEntrySchema>} PresenceEntry
 * @typedef {import("@sinclair/typebox").Static<typeof import("./snapshot.js").StateVersionSchema>} StateVersion
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agent.js").AgentEventSchema>} AgentEvent
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agent.js").AgentIdentityParamsSchema>} AgentIdentityParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agent.js").AgentIdentityResultSchema>} AgentIdentityResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agent.js").PollParamsSchema>} PollParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agent.js").AgentWaitParamsSchema>} AgentWaitParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agent.js").WakeParamsSchema>} WakeParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodePairRequestParamsSchema>} NodePairRequestParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodePairListParamsSchema>} NodePairListParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodePairApproveParamsSchema>} NodePairApproveParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodePairRejectParamsSchema>} NodePairRejectParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodePairVerifyParamsSchema>} NodePairVerifyParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodeRenameParamsSchema>} NodeRenameParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodeListParamsSchema>} NodeListParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodeDescribeParamsSchema>} NodeDescribeParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodeInvokeParamsSchema>} NodeInvokeParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodeInvokeResultParamsSchema>} NodeInvokeResultParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./nodes.js").NodeEventParamsSchema>} NodeEventParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./sessions.js").SessionsListParamsSchema>} SessionsListParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./sessions.js").SessionsPreviewParamsSchema>} SessionsPreviewParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./sessions.js").SessionsResolveParamsSchema>} SessionsResolveParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./sessions.js").SessionsPatchParamsSchema>} SessionsPatchParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./sessions.js").SessionsResetParamsSchema>} SessionsResetParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./sessions.js").SessionsDeleteParamsSchema>} SessionsDeleteParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./sessions.js").SessionsCompactParamsSchema>} SessionsCompactParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./config.js").ConfigGetParamsSchema>} ConfigGetParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./config.js").ConfigSetParamsSchema>} ConfigSetParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./config.js").ConfigApplyParamsSchema>} ConfigApplyParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./config.js").ConfigPatchParamsSchema>} ConfigPatchParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./config.js").ConfigSchemaParamsSchema>} ConfigSchemaParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./config.js").ConfigSchemaResponseSchema>} ConfigSchemaResponse
 * @typedef {import("@sinclair/typebox").Static<typeof import("./wizard.js").WizardStartParamsSchema>} WizardStartParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./wizard.js").WizardNextParamsSchema>} WizardNextParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./wizard.js").WizardCancelParamsSchema>} WizardCancelParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./wizard.js").WizardStatusParamsSchema>} WizardStatusParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./wizard.js").WizardStepSchema>} WizardStep
 * @typedef {import("@sinclair/typebox").Static<typeof import("./wizard.js").WizardNextResultSchema>} WizardNextResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./wizard.js").WizardStartResultSchema>} WizardStartResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./wizard.js").WizardStatusResultSchema>} WizardStatusResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./channels.js").TalkModeParamsSchema>} TalkModeParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./channels.js").ChannelsStatusParamsSchema>} ChannelsStatusParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./channels.js").ChannelsStatusResultSchema>} ChannelsStatusResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./channels.js").ChannelsLogoutParamsSchema>} ChannelsLogoutParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./channels.js").WebLoginStartParamsSchema>} WebLoginStartParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./channels.js").WebLoginWaitParamsSchema>} WebLoginWaitParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentSummarySchema>} AgentSummary
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentsFileEntrySchema>} AgentsFileEntry
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentsFilesListParamsSchema>} AgentsFilesListParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentsFilesListResultSchema>} AgentsFilesListResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentsFilesGetParamsSchema>} AgentsFilesGetParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentsFilesGetResultSchema>} AgentsFilesGetResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentsFilesSetParamsSchema>} AgentsFilesSetParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentsFilesSetResultSchema>} AgentsFilesSetResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentsListParamsSchema>} AgentsListParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").AgentsListResultSchema>} AgentsListResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").ModelChoiceSchema>} ModelChoice
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").ModelsListParamsSchema>} ModelsListParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").ModelsListResultSchema>} ModelsListResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").SkillsStatusParamsSchema>} SkillsStatusParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").SkillsBinsParamsSchema>} SkillsBinsParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").SkillsBinsResultSchema>} SkillsBinsResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").SkillsInstallParamsSchema>} SkillsInstallParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./agents-models-skills.js").SkillsUpdateParamsSchema>} SkillsUpdateParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./cron.js").CronJobSchema>} CronJob
 * @typedef {import("@sinclair/typebox").Static<typeof import("./cron.js").CronListParamsSchema>} CronListParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./cron.js").CronStatusParamsSchema>} CronStatusParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./cron.js").CronAddParamsSchema>} CronAddParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./cron.js").CronUpdateParamsSchema>} CronUpdateParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./cron.js").CronRemoveParamsSchema>} CronRemoveParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./cron.js").CronRunParamsSchema>} CronRunParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./cron.js").CronRunsParamsSchema>} CronRunsParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./cron.js").CronRunLogEntrySchema>} CronRunLogEntry
 * @typedef {import("@sinclair/typebox").Static<typeof import("./logs-chat.js").LogsTailParamsSchema>} LogsTailParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./logs-chat.js").LogsTailResultSchema>} LogsTailResult
 * @typedef {import("@sinclair/typebox").Static<typeof import("./exec-approvals.js").ExecApprovalsGetParamsSchema>} ExecApprovalsGetParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./exec-approvals.js").ExecApprovalsSetParamsSchema>} ExecApprovalsSetParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./exec-approvals.js").ExecApprovalsNodeGetParamsSchema>} ExecApprovalsNodeGetParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./exec-approvals.js").ExecApprovalsNodeSetParamsSchema>} ExecApprovalsNodeSetParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./exec-approvals.js").ExecApprovalsSnapshotSchema>} ExecApprovalsSnapshot
 * @typedef {import("@sinclair/typebox").Static<typeof import("./exec-approvals.js").ExecApprovalRequestParamsSchema>} ExecApprovalRequestParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./exec-approvals.js").ExecApprovalResolveParamsSchema>} ExecApprovalResolveParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./devices.js").DevicePairListParamsSchema>} DevicePairListParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./devices.js").DevicePairApproveParamsSchema>} DevicePairApproveParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./devices.js").DevicePairRejectParamsSchema>} DevicePairRejectParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./devices.js").DeviceTokenRotateParamsSchema>} DeviceTokenRotateParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./devices.js").DeviceTokenRevokeParamsSchema>} DeviceTokenRevokeParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./logs-chat.js").ChatAbortParamsSchema>} ChatAbortParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./logs-chat.js").ChatInjectParamsSchema>} ChatInjectParams
 * @typedef {import("@sinclair/typebox").Static<typeof import("./logs-chat.js").ChatEventSchema>} ChatEvent
 * @typedef {import("@sinclair/typebox").Static<typeof import("./config.js").UpdateRunParamsSchema>} UpdateRunParams
 */
