const PROJECT_NAME = 'openclaw';
const LEGACY_PROJECT_NAMES = [];
const MANIFEST_KEY = PROJECT_NAME;
const LEGACY_MANIFEST_KEYS = LEGACY_PROJECT_NAMES;
const LEGACY_PLUGIN_MANIFEST_FILENAMES = [];
const LEGACY_CANVAS_HANDLER_NAMES = [];
const MACOS_APP_SOURCES_DIR = 'apps/macos/Sources/OpenClaw';
const LEGACY_MACOS_APP_SOURCES_DIRS = [];
export {
  LEGACY_CANVAS_HANDLER_NAMES,
  LEGACY_MACOS_APP_SOURCES_DIRS,
  LEGACY_MANIFEST_KEYS,
  LEGACY_PLUGIN_MANIFEST_FILENAMES,
  LEGACY_PROJECT_NAMES,
  MACOS_APP_SOURCES_DIR,
  MANIFEST_KEY,
  PROJECT_NAME
};
